### ISSUE TITLE
Export to JSON

### ISSUE THREAD

**Issue by patriciog** [darkdukey/Cocos-Studio#34]
Hi guys:

We're using Cocos Studio 2.0.2 with Cocos2d-js 3.1, but I've seen this notice into Cocos2d-js 3.2 rc0 release-note:

```
Cocos2d-JS v3.2 is compatible with Cocos Studio v1.2 - v1.6, Cocos Studio 2 support have been removed because flat buffer binary file can't be parsed in JS, we will support Cocos Studio 2 in v3.3 with a JSON format parser.
```

I suppose the feature 'Export to JSON' will be a feature of Cocos Studio 2 in the future. I've installed Cocos Studio 2 version 2.0.6, but it doesn't implement this feature.

- When are you planning to integrate this feature?

- Will I be able to convert my Cocos Studio 2.0.2 projects to this version and export to JSON?

Thanks for advance,

Patricio.

**Comment by kienvn** [comment]
I really need this future too.

**Comment by benrecm** [comment]
This would be useful for me too. We are still stuck using CocoStudio 1.6 as our projects rely on cocos2d-x 2.2 using the JSON parser.

**Comment by darkdukey** [comment]
Good news guys json export is supported by v2.1
