### ISSUE TITLE
crash when trying to use a label (new in 2.2.6)

### ISSUE THREAD

**Issue by araker** [darkdukey/Cocos-Studio#62]
Hello, 

I'm using cocos2d-x JS 3.5 and cocos studio 2.2.6. 

Steps to reproduce the problem.

Create a new project with lua or js
Add a label to the scene. 
The program hangs. 

I didn't have this problem in 2.2.5.

**Comment by josempans** [comment]
Are you using Win or Mac? In my experience, using Mac, it also seems to hang, but it's not what happen. Once I drop a label, and I went for a coffee... When I've returned, the label was there, :). It's a problem that occurs with any widget.

**Comment by araker** [comment]
Well in 2.2.8 the problem is gone again. It now appears within seconds, so this bug isn't relevant anymore.
